config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get '/', to: 'welcome#index'

  get '/roles', to: 'users#show'
  post '/roles', to: 'user_role#update'

  get '/artists/register', to: 'artists#new'
  post '/artists/register', to: 'artists#create'
  get '/artists/import', to: 'artists#import'
  patch '/artists/register', to: 'artists#update'
  get '/artists/dashboard', to: 'artists#show'
  delete '/artists/:id', to: 'artists#delete'

  get '/venues', to: 'venues#index'
  get '/venues/register', to: 'venues#new'
  post '/venues/register', to: 'venues#create'
  get '/venues/edit', to: 'venues#edit'
  patch '/venues/edit', to: 'venues#update'
  get '/venues/dashboard', to: 'venues#show'
  patch '/venues/dashboard', to: 'venue_artists#update'
  delete '/venues/dashboard', to: 'venues#destroy'

  get '/auth/google_oauth2', as: :google_login
  get '/auth/google_oauth2/callback', to: 'users#create'
  delete '/logout', to: 'users#destroy'
  
  resources :artists, only: [:show]
  delete '/artists/:id', to: 'artists#delete'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true
  validates :name, presence: true
   

   enum role: %w(default artist venue)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    @current_user = User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index; end

  def show
    @artist = ArtistFacade.artist_details(params[:id])
  end

  def new
    data = { name: '', location: '', genre: '', bio: '', image_path: '/assets/images/no_image_icon.png' }
    @imported = Artist.new(data)
  end

  def import
    if params[:name].nil?
      flash[:error] = 'Name cannot be blank'
      redirect_to '/artists/register'
    else
      @imported = ArtistFacade.artist_import(params[:name])
      render action: :new
    end
  end

  def create
    response = ArtistService.artist_create(artist_params)
    if !response.nil?
      flash[:success] = 'Registration Complete!'
      redirect_to artist_path(params[:user_id])
    else
      flash[:error] = response
    end
  end

  def update
    user = current_user
    ArtistService.artist_update(user.id, artist_params)
    redirect_to '/artists/dashboard'
  end

  def delete
    binding.pry
    response = ArtistService.artist_delete(params[:id])
  end
  private

  def artist_params
    params.permit(:user_id, :name, :location, :genre, :bio, :image_path)
  end
end

app/controllers/user_role_controller.rb
class UserRoleController < ApplicationController
  def update
    user = current_user
    user.update(user_role_params)
    if user.role == 'artist'
      redirect_to '/artists/register'
    elsif user.role == 'venue'
      redirect_to '/venues/register'
    end
  end

  private
  def user_role_params
    params.permit(:role)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    user = current_user
    if user.role == 'venue'
      redirect_to '/venues/dashboard'
    elsif user.role == 'artist'
      redirect_to '/artists/dashboard'
    else
    end
  end
 
  def create
    auth_hash = request.env['omniauth.auth']
    user = User.find_or_create_by(email: auth_hash[:info][:email], name: auth_hash[:info][:name])
    session[:user_id] = user.id
    session[:user_token] = auth_hash[:credentials][:token]
    redirect_to '/roles'
  end

  def destroy
    session.destroy
    redirect_to root_path
    flash[:success] = "You've succesfully logged out."
  end


  private
  def user_params
    params.require(:user).permit(:email, :name)
  end
end

app/controllers/venue_artists_controller.rb
class VenueArtistsController < ApplicationController
  # def update
  #   venue_artist = #code that works with facade/service to retrieve venue artist
  #   if params[:booking_status] == 1
  #     venue_artist
  # end
end

app/controllers/venues/dashboard_controller.rb
class Venues::DashboardController < ApplicationController
  def index
    user = current_user
    @venue = VenueFacade.find_venue(user.id)
  end
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  def index; end

  def show
    user = current_user
    @venue = VenueFacade.find_venue(user.id)
  end

  def new
    @user = current_user
  end

  def create
    VenueService.new_venue(venue_params)
    redirect_to '/venues/dashboard'
  end

  def edit
    @user = current_user
    @venue = VenueFacade.find_venue(@user.id)
  end

  def update
    user = current_user
    VenueService.update_venue(user.id, venue_params)
    redirect_to '/venues/dashboard'
  end

  def destroy
    user = current_user
    VenueService.delete_venue(user.id)
    session.destroy
    user.role = 'default'
    redirect_to root_path
  end

  private
  def venue_params
    params.permit(:name, :location, :phone, :price, :category, :rating, :user_id)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/artists/new.html.erb
<center><h1>Artist Registration Page</h1></center>
<b><b>
<center><div id = "artist-import">
  <%= image_tag "341104_last.fm_icon.png", height: 48 %> 
  <%= form_with url: artists_import_path, method: :get, local: true do |f| %>
    <%= f.label :name, "Artist Name (required):" %>
    <%= f.text_field :name %>
    <%= f.submit "Import from Last.fm" %>
<% end %>
</div></center>
<b><b>
<center><div id="artist-form">
  <%= form_with url: artists_register_path, method: :post, local: true do |f| %>
    <%= f.label :name, "Name:" %>
    <%= f.text_field :name, value: @imported.name %><b><b>
    <%= f.label :location, "Location:" %>
    <%= f.text_field :location, value: @imported.location %><b><b>
    <%= f.label :genre, "Genre:" %>
    <%= f.text_field :genre, value: @imported.genre %><b><b>
    <%= f.label :bio, "Tell me about yourself:" %>
    <%= f.text_field :bio, value: @imported.bio %><b><b>
    <%= f.hidden_field :image_path, value: @imported.image_path%>
    <%= f.hidden_field :user_id, value: session[:user_id] %>
    <%= f.submit "Complete Registration" %><b><b>
  <% end %>
 </div></center>

app/views/artists/show.html.erb
 <input class="form-control form-control-dark w-100" type="text" placeholder="Search for venues" aria-label="Search">
</div>
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2 mr-auto"><%= @artist.name%>( <%= @artist.genre %>)</h1>
    <a class="btn btn-outline-primary mx-2" href="#" role="button">Edit profile</a>
    <%= button_to 'Delete Profile', '/artists/dashboard', method: :delete, class: 'btn btn-outline-danger' %>
  </div>
  <img src="https://iscale.iheart.com/catalog/artist/179" width=200 length=250>
  <h4>Location: <%= @artist.location %></h4>
  <h4>Bio: <%= @artist.bio %></h4><br>
  


  <h2>My Venues</h2>
  <div class="table-responsive">
    <table class="table table-striped table-sm">
      <thead>
        <tr>
          <th>Venue Name</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>Brooklyn Bowl</td>
        </tr>
        <tr>
          <td>Terminal 5</td>
        </tr>
      </tbody>
    </table>
  </div>

  <br>

  <h2>Pending Bookings</h2>
  <div class="table-responsive">
    <table class="table table-striped table-sm">
      <thead>
        <tr>
          <th>Venue Name</th> 
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>Madison Square Garden</td>
        </tr>
      </tbody>
    </table>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BandAid</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <% flash.each do |type, msg| %>
      <div class="flash-notice">
        <%= msg %>
      </div>
    <% end %>
  <nav class="site-header sticky-top py-1 bg-dark">
    <div class="container d-flex flex-column flex-md-row justify-content-between">
      <a class="py-2 d-none d-md-inline-block text-white" href="/">Home</a>
      <% if session[:user_id] %>
      <%= link_to 'Logout', '/logout', method: :delete, class: 'py-2 d-none d-md-inline-block text-white' %>
      <% else %>
      <% end %>
    </div>
  </nav>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-light">
  <div class="col-md-5 p-lg-5 mx-auto my-5">
    <h1 class="display-3 font-weight-normal">BandAid</h1>
      <div class ='btn-group' role='group'>
        <center><%= button_to 'I am an artist', '/roles', class: 'btn btn-warning btn-lg active my-5 mx-3 text-white', params: { role: 'artist' } %></center>
        <center><%= button_to 'I am a venue/booker', '/roles', class: 'btn btn-danger btn-lg active my-5 mx-3', params: { role: 'venue' } %></center>
      </div>
  </div>
</div>

app/views/venues/dashboard/index.html.erb
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2 mr-auto"><%= @venue.name %><%= "(#{@venue.category})" %></h1>
    <%= button_to 'Edit Profile', '/venues/edit', method: :get, class: 'btn btn-outline-primary mx-2' %>
    <%= button_to 'Delete Profile', '/venues/dashboard', method: :delete, class: 'btn btn-outline-danger' %>
  </div>
  
  <h4>Address:<%= @venue.location %></h4>
  <h4>Phone:<%= @venue.phone %> </h4><br>
  <h4>Price: <%= @venue.price %></h4>
  <h4>Yelp Rating: <%= @venue.rating %></h4><br>
  


  <h2>Booked Artists</h2>
  <div class="table-responsive">
    <table class="table table-striped table-sm">
      <thead>
        <tr>
          <th>Artist Name</th>
        </tr>
      </thead>
      <tbody>
        <% @venue.bookings.each do |artist| %>
          <% if artist[:booking_status] == 1 %>
          <tr>
            <td><%= link_to "#{artist[:artist_name]}", "/artist/dashboard" %></td>
          </tr>
          <% else %>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>

  <br>

  <h2>Artists Requesting to Play at Venue</h2>
  <div class="table-responsive">
    <table class="table table-striped table-sm">
      <thead>
        <tr>
          <th>Artist Name</th>
          <th>Approve?</th>
          <th>Deny?</th>
        </tr>
      </thead>
      <tbody>
        <% @venue.bookings.each do |artist| %>
          <% if artist[:booking_status] == 0 %>
          <tr>
            <td><%= link_to "#{artist[:artist_name]}", "/artists/dashboard" %></td>
            <td><%= button_to "Approve", "/venues/dashboard", method: :patch, params: {booking_status: 1}, class: 'btn btn-outline-primary' %>
            <td><%= button_to "Deny", "/venues/dashboard", method: :patch, params: {booking_status: 2}, class: 'btn btn-outline-primary' %>
          </tr>
          <% else %>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</main>

app/views/venues/edit.html.erb
<h1>Edit Venue</h1>
<%= form_with url: '/venues/edit', method: :patch, local: true do |f| %>

  <%= f.label :name, "Name:" %>
  <%= f.text_field :name, value: @venue.name %>

  <%= f.label :location, "Location:" %>
  <%= f.text_field :location, value: @venue.location %>

  <%= f.label :phone, "Phone:" %>
  <%= f.telephone_field :phone, value: @venue.phone %>

  <%= f.label :category, "Category:" %>
  <%= f.text_field :category, value: @venue.category %>
  
  <%= f.label :price, "Price:" %>
  <%= f.select :price, ['$', '$$', '$$$', '$$$$'], value: @venue.price %>
  
  <%= f.hidden_field :rating, value: nil %>
  <%= f.hidden_field :user_id, value: @user.id %>

  <%= f.submit %>
<% end %>

app/views/venues/index.html.erb
<h2>All Venues</h2><br>
  <div class="table-responsive">
    <table class="table table-striped table-sm mx-3">
      <thead>
        <tr>
          <th>Venue Name</th>
          <th>Location</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>Brooklyn Bowl</td>
          <td>Brooklyn</td>
        </tr>
        <tr>
          <td>Terminal 5</td>
          <td>Manhattan</td>
        </tr>
        <tr>
          <td>Red Rocks Ampitheater</td>
          <td>Denver?</td>
        </tr>
        <tr>
          <td>Carnegie Hall</td>
          <td>Manhattan</td>
        </tr>
      </tbody>
    </table>
  </div>

app/views/venues/new.html.erb
<center><h1>New Venue Registration</h1></center>


<center><%= link_to "Import Yelp Profile" %>

<%= form_with url: '/venues/register', method: :post, local: true do |f| %>

  <%= f.label :name, "Name:" %>
  <%= f.text_field :name %><b><b>

  <%= f.label :location, "Location:" %>
  <%= f.text_field :location %><b><b>

  <%= f.label :phone, "Phone:" %>
  <%= f.telephone_field :phone %><b><b>

  <%= f.label :category, "Category:" %>
  <%= f.text_field :category %><b><b>
  
  <%= f.label :price, "Price:" %>
  <%= f.select :price, ['$', '$$', '$$$', '$$$$'] %><b><b>
  
  <%= f.hidden_field :rating, value: nil %>
  <%= f.hidden_field :user_id, value: @user.id %><b><b>

  <%= f.submit %><b><b>
<% end %></center>

app/views/venues/show.html.erb
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2 mr-auto"><%= @venue.name %><%= "(#{@venue.category})" %></h1>
    <a class="btn btn-outline-primary mx-2" href="#" role="button">Edit profile</a>
    <a class="btn btn-outline-danger" href="#" role="button">Delete profile</a>
  </div>
  
  <h4>Address:<%= @venue.location %></h4>
  <h4>Phone:<%= @venue.phone %> </h4><br>
  <h4>Price: <%= @venue.price %></h4>
  <h4>Yelp Rating: <%= @venue.rating %></h4><br>
  


  <h2>Booked Artists</h2>
  <div class="table-responsive">
    <table class="table table-striped table-sm">
      <thead>
        <tr>
          <th>Artist Name</th>
        </tr>
      </thead>
      <tbody>
        <% @venue.bookings.each do |artist| %>
          <% if artist[:booking_status] == 1 %>
          <tr>
            <td><%= link_to "#{artist[:artist_name]}", "/artist/dashboard" %></td>
          </tr>
          <% else %>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>

  <br>

  <h2>Artists Requesting to Play at Venue</h2>
  <div class="table-responsive">
    <table class="table table-striped table-sm">
      <thead>
        <tr>
          <th>Artist Name</th>
          <th>Approve?</th>
          <th>Deny?</th>
        </tr>
      </thead>
      <tbody>
        <% @venue.bookings.each do |artist| %>
          <% if artist[:booking_status] == 0 %>
          <tr>
            <td><%= link_to "#{artist[:artist_name]}", "/artists/dashboard" %></td>
            <td><%= button_to "Approve", "/venues/dashboard", method: :patch, params: {booking_status: 1}, class: 'btn btn-outline-primary' %>
            <td><%= button_to "Deny", "/venues/dashboard", method: :patch, params: {booking_status: 2}, class: 'btn btn-outline-primary' %>
          </tr>
          <% else %>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</main>

app/views/welcome/index.html.erb
<div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-light">
  <div class="col-md-5 p-lg-5 mx-auto my-5">
    <h1 class="display-3 font-weight-normal">BandAid</h1>
    <p class="lead font-weight-normal">Helping bands and venues find one another to make booking gigs easier.</p>
    <center><img src="https://www.freepnglogos.com/uploads/google-logo-png/google-logo-png-webinar-optimizing-for-success-google-business-webinar-13.png" width=75 length=75/></center>
    <a class="btn btn-outline-secondary" href="/auth/google_oauth2">Sign In / Sign Up Using Google</a>
  </div>
</div>

<div class="d-md-flex flex-md-equal w-100 my-md-3 pl-md-3">
  <div class="bg-warning mr-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center text-white flex-fill overflow-hidden">
    <div class="my-3 py-3">
      <h2 class="display-5">Artist?</h2>
      <p class="lead">Let us help you find the perfect place for your next gig.</p>
    </div>
    <div class="bg-light shadow-sm mx-auto" style="width: 80%; height: 0px; border-radius: 21px 21px 0 0;"></div>
  </div>
  <div class="bg-danger mr-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center text-white flex-fill overflow-hidden">
    <div class="my-3 py-3">
      <h2 class="display-5">Venue?</h2>
      <p class="lead">Let us help find the best artist for your next event.</p>
    </div>
    <div class="bg-light shadow-sm mx-auto" style="width: 80%; height: 0px; border-radius: 21px 21px 0 0;"></div>
  </div>
</div>